### ISSUE TITLE
OFAC service can fail on start-up

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/ofac#109]
If the OFAC service has a failure getting the sanctions list it will exit with a failure.  I'm not sure this is the most ideal behavior.

Maybe it should keep trying?  Maybe it can try from some back up locations?  Not sure the best behavior but crashing does not seem ideal.

(Note: we are not currently persisting the DB.  So maybe this is a problem only on initial run when db is created?)

**Comment by adamdecaf** [comment]
Yea. I've noticed it too, so let's retry the download. I've thought about an env variable to specify a directory for downloads (rather than a temporary directory) which could be persisted, but haven't written that code.
