### ISSUE TITLE
Retry mechanism could be better

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/ofac#112]
I think when the ofac site is having trouble it has bigger troubles than a retry will solve!  :(

Also, I see this error when it fails:
{"caller":"main.go:135","main":"ERROR: failed to download/parse initial OFAC data: ERROR: downloading OFAC and DPL data: OFAC: problem downloading (matched=add.csv, alt.csv, sdn.csv, sdn_comments.csv missing=dpl.txt): err=\u003cnil\u003e","ts":"2019-08-07T04:40:48.491283209Z"}

Something weird is happening with the error field.

An option to load from disk or something would be nice for dev...

**Comment by adamdecaf** [comment]
I created two pull requests @rayjlinden that should address this.
