### ISSUE TITLE
Results inconsistent with Treasury.gov

### ISSUE THREAD

**Issue by brobits** [moov-io/ofac#115]
Using this service (or the example available at https://moov.io/ofac/) does not match results from the treasury's official SDN search at https://sanctionssearch.ofac.treas.gov/.

This service returns way too many unrelated results with a high match value. For example, searching "George Bush" returns an 89% match to "George Habbash", 88% match to "George Haswani", 84% match to "George Chiweshe":

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/1591028/62962903-863f1980-bdc5-11e9-900b-17d957803dc3.png">

However, searching the same name with an 80% fuzzy match threshold on the Treasury's own OFAC search website yields no results:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/1591028/62962819-5859d500-bdc5-11e9-95f1-a76f9e33befa.png">

I love the open source fintech toolbox. Unfortunately these tools are not high enough quality to use in production at a financial institution today. I look forward to helping to improve the library.

Thanks!

**Comment by adamdecaf** [comment]
@brobits Thanks for the report. I'm not quite sure how OFAC's site performs similarity calculations, but I [opened a pull request](https://github.com/moov-io/ofac/pull/116) to help address this. Any advice you have would be much appreciated!

**Comment by brobits** [comment]
Hi, @adamdecaf! Thanks for taking a look at this. I'm not sure what the Treasury uses for their fuzzy logic matching, but I found a thread discussing a few algorithms here: https://www.bankersonline.com/forum/ubbthreads.php/topics/2147612/ofac-fuzzy-logic-recommendations

They mention the Jaro-Winkler algorithm which I believe this library also uses (https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance). They also mention the Soundex (https://en.wikipedia.org/wiki/Soundex) algorithm. I assume the Treasury also uses Jaro-Winkler?

**Comment by adamdecaf** [comment]
OFAC uses jaro-winkler, yes. I picked it over Levenshtein and Jaro because of the improvements it provides. 

We could support soundex (probably by setting `&algorithm=soundex` in the URL), but I'd like to harden the current usage of jaro-winkler.

**Comment by brobits** [comment]
Awesome! Thanks for the insight, no worries about alternative implementations provided results are similar enough to the Treasury. Thanks again for taking a look at this so quickly.

**Comment by adamdecaf** [comment]
v0.10.0 will be released today with this included

**Comment by brobits** [comment]
fantastic, thanks for the heads up. we're seeing more reliable results now.

I'll see if I can steal some time from our compliance team in the next weeks to give me some feedback

**Comment by adamdecaf** [comment]
Sounds great! We should be able to improve the matching too if your team finds issues.
