### ISSUE TITLE
OFAC dies when it can not load the OFAC info 

### ISSUE THREAD

**Issue by rayjlinden** [moov-io/ofac#118]
The treasury site where this service downloads info is not the greatest about being always available.

Recently, a retry mechanism was added.  This may have helped in some cases. However, we still see a lot of failures.

The big problem we have is that when it can not load the data the container dies.  In our docker-compose environment we have nginx running in front of it and the container then kills our nginx container which means we have to restart the whole damn thing.

(This will be a little less of a problem in production because we could just leave old containers up until new containers successfully launch and load the data.)

At least in our sandbox environment it would be nice if we could load these files initially from disk.  Then worse case the data is not fresh - but at least the container is up and running.

**Comment by adamdecaf** [comment]
I added support for `INITIAL_DATA_DIRECTORY=/data/` which looks for `sdn.csv`, `dpl.txt` (and other files) to bypass the initial download.

**Comment by adamdecaf** [comment]
Are you talking about on a refresh if we fail the container exits? We should probably just skip the update in that case.

**Comment by rayjlinden** [comment]
Oh my!  I missed the INITIAL_DATA_DIRECTORY thing!  Dang, your awesome!
Just got it integrated.  Thank you!

I have yet to see it fail on a refresh (or have not noticed) - but yea, it should not panic if it can not do the refresh!!!
