### ISSUE TITLE
Add Type filter for the search

### ISSUE THREAD

**Issue by stoutlinden** [moov-io/ofac#133]
One of the important filters we will need is the Type filter that lets us distinguish individuals from other types of entities. I'd be happy to add it to the UI once the search API supported this.

![image](https://user-images.githubusercontent.com/50342389/65795379-fb20a580-e11e-11e9-9b2c-cab35b9c3686.png)

**Comment by adamdecaf** [comment]
@stoutlinden I think I've got this working now: 

https://gist.github.com/adamdecaf/6d9ec68dbce0308695057953dc38a0a2

**Comment by adamdecaf** [comment]
<img width="852" alt="Screen Shot 2019-09-27 at 4 19 45 PM" src="https://user-images.githubusercontent.com/120951/65807445-5a90ac80-e143-11e9-8664-8eda15f5bd12.png">
