### ISSUE TITLE
OFAC not returning matches

### ISSUE THREAD

**Issue by dacrypt** [moov-io/ofac#141]
I've been trying to get ofac to work but it doesn't seem to be returning the rigth results:
 
1. Go to https://sanctionssearch.ofac.treas.gov/ and search name="Maduro" (the venezuelan dictator) and you will get 4 results with 100% score.
2. Go to https://moov.io/ofac/ and search "Maduro" and you won't get those 4 results but a bunch of unrelated results

Also if you search by the National ID Number you won't get any results:
1. Go to https://sanctionssearch.ofac.treas.gov/ and search ID#="5892464" and you will get the right result of "Maduro"
2. Go to https://moov.io/ofac/ and search "5892464" and just a bunch of nonsense is returned.  (Also tried using a recent ofac docker image with search/q=589246)

**Comment by adamdecaf** [comment]
I've designed the search rankings to compare the entire SDN name against the search query, but it looks like their engine would match a single word at 100%. Technically "Maduro" doesn't match Nicolas MADURO MOROS (case is ignored in our app) at 100%, so I don't understand what their score represents. 

That said I use Maduro as an example myself and wish "Nicolas Maduro" matched higher. To do this I think we need some country/region aware name parsing so that we could ignore a middle name if the query doesn't specify one.

**Comment by adamdecaf** [comment]
Re: ID queries. I noticed this before, but haven't done anything to parse `No. 0000000`, but we can add that functionality. My initial thought would be to compare against that in `/search?q=0000000` and `/search?id=0000000` (but not, say `/search?name=0000000`).

**Comment by dacrypt** [comment]
> I've designed the search rankings to compare the entire SDN name against the search query, but it looks like their engine would match a single word at 100%. Technically "Maduro" doesn't match Nicolas MADURO MOROS (case is ignored in our app) at 100%, so I don't understand what their score represents.
> 
> That said I use Maduro as an example myself and wish "Nicolas Maduro" matched higher. To do this I think we need some country/region aware name parsing so that we could ignore a middle name if the query doesn't specify one.

They explain how the matching works here: https://www.treasury.gov/RESOURCE-CENTER/SANCTIONS/SDN-List/Pages/fuzzy_logic.aspx

**Comment by adamdecaf** [comment]
I have a change for OFAC to parse the ID values in each remarks property (No. 312451) and used in queries of the form `/search?q=312451` and `/search?id=312451`. This lets us find Maduro right away.

```
$ curl -s "http://localhost:8084/search?limit=2&id=5892464" | jq . 
{
  "SDNs": [
    {
      "entityID": "22790",
      "sdnName": "MADURO MOROS, Nicolas",
      "sdnType": "individual",
      "program": "VENEZUELA",
      "title": "President of the Bolivarian Republic of Venezuela",
      "callSign": "",
      "vesselType": "",
      "tonnage": "",
      "grossRegisteredTonnage": "",
      "vesselFlag": "",
      "vesselOwner": "",
      "remarks": "DOB 23 Nov 1962; POB Caracas, Venezuela; citizen Venezuela; Gender Male; Cedula No. 5892464 (Venezuela); President of the Bolivarian Republic of Venezuela.",
      "match": 0
    }
  ],
  "altNames": null,
  "addresses": null,
  "deniedPersons": null
}
```

```
$ curl -s "http://localhost:8084/search?limit=2&q=5892464" | jq .SDNs 
[
  {
    "entityID": "22790",
    "sdnName": "MADURO MOROS, Nicolas",
    "sdnType": "individual",
    "program": "VENEZUELA",
    "title": "President of the Bolivarian Republic of Venezuela",
    "callSign": "",
    "vesselType": "",
    "tonnage": "",
    "grossRegisteredTonnage": "",
    "vesselFlag": "",
    "vesselOwner": "",
    "remarks": "DOB 23 Nov 1962; POB Caracas, Venezuela; citizen Venezuela; Gender Male; Cedula No. 5892464 (Venezuela); President of the Bolivarian Republic of Venezuela.",
    "match": 0
  }
]
```

**Comment by adamdecaf** [comment]
I've opened https://github.com/moov-io/ofac/pull/143 and https://github.com/moov-io/ofac/pull/144 to address both major points in this issue.
