### ISSUE TITLE
latest ofac version requires an invalid go4.org pseudo-version

### ISSUE THREAD

**Issue by dmitshur** [moov-io/ofac#167]
In commit 9844e58018f379b5bc948813edba6ff91df80449, the go4.org module requirement was updated to an invalid pseudo-version. In commit 6e70f243f0c77aab203053a0d91edfba36a534e1, a replace directive was added with the correct pseudo-version.

A problem is that the replace directive only applies when this is the main module, so it doesn't help other projects that try to require and use this module.

You can reproduce by doing:

```
$ go version
go version go1.13.4 darwin/amd64
$ cd $(mktemp -d)
$ go mod init example.com/m
go: creating new go.mod: module example.com/m
$ go get github.com/moov-io/ofac@latest
go: finding github.com/moov-io/ofac v0.11.1
go: downloading github.com/moov-io/ofac v0.11.1
go: extracting github.com/moov-io/ofac v0.11.1
go get: github.com/moov-io/ofac@v0.11.1 requires
	go4.org@v0.0.0-20190430205326-94abd6928b1d: invalid pseudo-version: does not match version-control timestamp (2019-03-13T08:23:47Z)
```

The right fix would be to remove the replace directive and change the required version to be valid.

**Comment by adamdecaf** [comment]
Thanks for bringing this up. I've released an RC version which should fix this, but I plan for a proper v0.12.0 release today.
