### ISSUE TITLE
Remove replaceNull function

### ISSUE THREAD

**Issue by bkmoovio** [moov-io/ofac#24]
Remove replaceNull function

**Comment by adamdecaf** [comment]
@bkmoovio I was using this in [an open PR](https://github.com/moov-io/ofac/pull/23/commits/42ae432143b3129532f0aa8e9d4b7903caa031de) to cleanup the data. I don't want the HTTP API to return `-0-`, but return an empty string instead.

**Comment by bkmoovio** [comment]
I didn't see it being used anywhere.  Do you want me to add it back in?
