### ISSUE TITLE
Possible match Exception or UnSafe 

### ISSUE THREAD

**Issue by wadearnold** [moov-io/ofac#37]
When a possible match occurs (above 85%) an endpoint should show the watch-list data that matched and the resulting score. 
The endpoint should allow the possible match result to be marked as `unsafe` or add an `exception` to avoid repeat matches of the same entry. 

`unsafe` the customer/company can no longer make payments

`exception` the customer/company had a false positive. An exception 

and `exception` should include the time, optional note, and ideally the user that made that decision.

**Comment by adamdecaf** [comment]
Sure. I think of a `customer_status` table with unique `(SDN.ID, userId)` and a status (`unsafe`, `exception`).

If no row assume no override and to return unsafe `if match > 0.85`. 
If row, return status 

Should we be `unsafe` on a db error?
